### ISSUE TITLE
 Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by gigo6000** [cloudinary/cloudinary_wordpress#413]
I just did a fresh install of the plugin using the Wordpress Plugins Directory (Wordpress -> plugins -> add new) and I got this warning on the admin (plugin settings):

```php

( ! ) Notice: Trying to access array offset on value of type null in .../wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/ui/class-component.php on line 483
```

```php

Notice: Trying to access array offset on value of type null in.../wp-content/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/ui/class-component.php on line 483
--


1 | 0.0007 | 368504 | {main}( ) | .../admin.php:0
2 | 0.5874 | 8715344 | do_action( ) | .../admin.php:259
3 | 0.5874 | 8715720 | WP_Hook->do_action( ) | .../plugin.php:484
4 | 0.5874 | 8715720 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:311
5 | 0.5874 | 8716848 | Cloudinary\Settings->render( ) | .../class-wp-hook.php:287
6 | 0.5874 | 8717680 | Cloudinary\UI\Component\Page->render( ) | .../class-settings.php:153
7 | 0.5942 | 8793064 | Cloudinary\UI\Component\Page->compile_structures( ) | .../class-component.php:326
8 | 0.5942 | 8793064 | Cloudinary\UI\Component\Page->handle_structure( ) | .../class-component.php:411
9 | 0.5942 | 8793064 | Cloudinary\UI\Component\Page->compile_part( ) | .../class-component.php:446

```

Here's the same warning on this tests: https://wphive.com/plugins/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/

Wordpress Version: 5.6
PHP: PHP 7.4.1
Ubuntu 18.04.3 LTS
Vagrant 2.2.9

**Comment by Vdeub-cloudinary** [comment]
Hi @gigo6000,
We have just released the `2.7.1` that should fix this issue. May I ask you to upgrade?
Thanks!

**Comment by gigo6000** [comment]
Hi @Vdeub-cloudinary, I upgraded to `2.7.1` and also upgraded Wordpress to `5.7.1` and I still see the warnings.

**Comment by Vdeub-cloudinary** [comment]
Hi @gigo6000, after checking with my team, the warning will be removed in `2.8.0` but you shouldn't have any issues with the `sync` process as they are just warning.
Hope that helps.
Best,

**Comment by pereirinha** [comment]
I self-assigned this ticket to ensure this is resolved in the next version.
Thank you.

**Comment by pereirinha** [comment]
Hello, @gigo6000 

This week we released Cloudinary `2.7.3`, and the version should resolve this issue.
Can you please confirm on your end?

Thank you.

**Comment by gigo6000** [comment]
Hello @pereirinha, I upgraded to `2.7.3` and I'm not seeing the error anymore, thanks

**Comment by Vdeub-cloudinary** [comment]
Hi @gigo6000, glad it is fixed!
